server:
  port: 8080
spring:
  application:
    name: EurekaClient
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: cxh
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

